name: dart_todo_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  build_cli_annotations: ^2.1.0
  enum_to_string: ^2.0.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  path: ^1.8.0
  uuid: ^4.4.0

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.9
  lints: ^2.1.0
  test: ^1.24.0
