import 'package:build_cli_annotations/build_cli_annotations.dart';

import 'common.dart';

part 'options.g.dart';

/// The command line argument parser generated by the `build_cli_annotations`
/// package.
ArgParser get parser => _$populateOptionsParser(ArgParser(allowTrailingOptions: false,usageLineLength: 80));

/// The command line options for this app
@CliOptions()
class Options {

  @CliOption(abbr: 'h', negatable: false, help: 'Prints usage information.')
  final bool help;

  final String add;

  final String list;

  final String remove;

  final String edit;

  final bool verbose;

  @CliOption(defaultsTo: Priority.medium, abbr: 'l')
  final Priority priority;

  Options(this.help, this.add, this.list, this.remove, this.edit, this.verbose, this.priority);
}




